version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  # database:
  #   image: mysql:latest
  #   container_name: database
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_USER: ducvq
  #     MYSQL_PASSWORD: root
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: weather
  #   ports:
  #     - 9306:3306
  #   volumes:
  #     - ./docker/database:/var/lib/mysql
